# This file was generated by GoReleaser. DO NOT EDIT.
cask "approach" do
  version "0.10.1"

  on_macos do
    on_intel do
      sha256 "2dd595e972d6f02b8695a0d7fff1f04e26d1f3f8dd9941512770da2133af1c03"
      url "https://github.com/approachcontrol/approach/releases/download/v#{version}/approach_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "8b0f7be8c4dff3f1f71622ac33d48a35c67ce3f1c0755067db15147de9a8c606"
      url "https://github.com/approachcontrol/approach/releases/download/v#{version}/approach_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "4c74ac245aa111f3b604c37002755b9595717764d354480af472f5f47f099ecd"
      url "https://github.com/approachcontrol/approach/releases/download/v#{version}/approach_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "883d0e624cf462b622b9e1a3b0bb84b28589e31ce086a218a951329a80b8747c"
      url "https://github.com/approachcontrol/approach/releases/download/v#{version}/approach_#{version}_linux_arm64.tar.gz"
    end
  end

  name "approach"
  desc "Terminal UI for managing git worktrees across repositories"
  homepage "https://github.com/approachcontrol/approach"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "approach"

  # No zap stanza required

end
