# This file was generated by GoReleaser. DO NOT EDIT.
cask "approach" do
  version "0.10.3"

  on_macos do
    on_intel do
      sha256 "5cdb482cfab896cb98dff2f3abdad2555e779d3f4f8e52a9f7a90602ca4a9512"
      url "https://github.com/approachcontrol/approach/releases/download/v#{version}/approach_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "677a85246059042b7c9c633a2ac82a5cf68820899a3b474ff45f350a1f51ae60"
      url "https://github.com/approachcontrol/approach/releases/download/v#{version}/approach_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "352d7189d642d4484042eb8221a519672c3d927d4ef594756544b12533f4b3ae"
      url "https://github.com/approachcontrol/approach/releases/download/v#{version}/approach_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "a90766d76ec37a524c912d3efc231ad4e3681df0369a75b36133e8177b9794a4"
      url "https://github.com/approachcontrol/approach/releases/download/v#{version}/approach_#{version}_linux_arm64.tar.gz"
    end
  end

  name "approach"
  desc "Terminal UI for managing git worktrees across repositories"
  homepage "https://github.com/approachcontrol/approach"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "approach"

  # No zap stanza required

end
