# This file was generated by GoReleaser. DO NOT EDIT.
cask "approach" do
  version "0.10.6"

  on_macos do
    on_intel do
      sha256 "6c50bccac9f246ade15adaf2e8f0a864619380db4023fa24e5f46c898e552dc1"
      url "https://github.com/approachcontrol/approach/releases/download/v#{version}/approach_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "10b5f31c832f28bb32110e17fe3ceff3b5ef01c6dfcf4b3dd1947025a020c4bf"
      url "https://github.com/approachcontrol/approach/releases/download/v#{version}/approach_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "d6fe6330a2d0b4ef80772ecf406c54234267a9d9c371b49ca1b587f793129db6"
      url "https://github.com/approachcontrol/approach/releases/download/v#{version}/approach_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "2cbba6c3aa59b2f85f2c411684f5f31875c7c738cb26a4d9e9b9bf00fbf6bbfa"
      url "https://github.com/approachcontrol/approach/releases/download/v#{version}/approach_#{version}_linux_arm64.tar.gz"
    end
  end

  name "approach"
  desc "Terminal UI for managing git worktrees across repositories"
  homepage "https://github.com/approachcontrol/approach"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "approach"

  # No zap stanza required

end
